name: OFX React-Front CI/CD flow

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build Docker
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: npm install

    - name: Build Next.js app
      run: npm run build

    - name: Build & push Docker image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: luisfj/ofx-front
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
  deploy_to_vps:
    name: Push to VPS
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          cd /srv;docker stop ofx-front;docker rm ofx-front;docker rmi luisfj/ofx-front;docker pull luisfj/ofx-front:latest;docker run -d -m 300m --network prodnet --name ofx-front luisfj/ofx-front
